on:
  push:
    branches:
      - main
  pull_request:
    types: [ assigned, opened, synchronize, reopened, labeled ]
name: ci
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 18]
    steps:
      - uses: actions/checkout@v3
      - run: git config --global user.name 'CI'
      - run: git config --global user.email 'dummy@example.org'
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - run: node --version
      - run: pnpm install
      - run: pnpm test
      - name: coverage
        uses: coverallsapp/github-action@master
        with:
          flag-name: actions ${{ matrix.node }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: git config --global user.name 'CI'
      - run: git config --global user.email 'dummy@example.org'
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm test-windows
      - name: coverage
        uses: coverallsapp/github-action@master
        with:
          flag-name: actions windows
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
  finish:
    needs: [test, windows]
    runs-on: ubuntu-latest
    steps:
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - name: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm install
          pnpm publish --no-git-checks --access public

